[package]
name = "raft"
version = "0.7.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["raft", "distributed-systems", "ha"]
repository = "https://github.com/tikv/raft-rs"
readme = "README.md"
homepage = "https://github.com/tikv/raft-rs"
documentation = "https://docs.rs/raft"
description = "The rust language implementation of Raft algorithm."
categories = ["algorithms", "database-implementations"]
edition = "2018"

[workspace]
members = ["datadriven", "harness", "proto"]

[features]
default = ["prost-codec", "default-logger"]
# Enable failpoints
failpoints = ["fail/failpoints"]
prost-codec = ["raft-proto/prost-codec"]
default-logger = ["slog-stdlog", "slog-envlogger", "slog-term"]

# Make sure to synchronize updates with Harness.
[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1"
bytes = { version = "1", optional = true }
fail = { version = "0.4", optional = true }
futures = "0.3"
fxhash = "0.2.1"
getset = "0.1.1"
prost = { version = "0.9" }
protobuf = "2"
raft-proto = { path = "proto", version = "0.7.0", default-features = false }
rand = "0.8"
serde = "1.0"
serde_derive = "1.0"
slog = "2.2"
slog-envlogger = { version = "2.1.0", optional = true }
slog-stdlog = { version = "4", optional = true }
slog-term = { version = "2.4.0", optional = true }
thiserror = "1.0"
tokio = { version = "1", features = [
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
] }

[dev-dependencies]
anyhow = "1.0.40"
criterion = { version = "0.3", features = ["async", "async_tokio"] }
datadriven = { path = "datadriven", version = "0.1.0" }
itertools = "0.10.0"
regex = "1"
slog-async = "2.3.0"
slog-envlogger = "2.1.0"
slog-stdlog = "4"
slog-term = "2.4.0"

[[bench]]
name = "benches"
harness = false

[[example]]
name = "single_mem_node"
path = "examples/single_mem_node/main.rs"

# Temporarily disabled.
# [[example]]
# name = "five_mem_node"
# path = "examples/five_mem_node/main.rs"
